add dog repository tests
bartek977/TrainingIntive pull request #55
Opened 2021-08-25 13:47 UTC by bartek977

2021-08-27 14:54 UTC, BorysChajdas requested changes

2021-08-27 14:54 UTC, BorysChajdas commented on app/src/test/java/com/example/trainingintive/dog_images_feature/data/repository/DogImageRepositoryImplTest.kt
> +    val urlApiModel = DogImageUrlApiModel("url", "status")
Avoid creating real objects when it isn't necessary. Create mocks and mock values if you need them. This way the test will be simpler and later on when you will change the model class you will not need to adjust every test.

2021-08-27 14:54 UTC, BorysChajdas commented on app/src/test/java/com/example/trainingintive/dog_images_feature/data/repository/DogImageRepositoryImplTest.kt
> +            .test()
extract it to `val result = ...`

2021-08-27 14:54 UTC, BorysChajdas commented on app/src/test/java/com/example/trainingintive/dog_images_feature/data/repository/DogImageRepositoryImplTest.kt
> +            .assertValue(urlApiModel.toDomain(amountUrlsInDb))
Avoid calling functions on real objects in the assertion. It will be better to mock `toDomain`. Read about mockK static mocking.

2021-08-27 15:02 UTC, bartek977 commented on app/src/test/java/com/example/trainingintive/dog_images_feature/data/repository/DogImageRepositoryImplTest.kt
> +    val urlApiModel = DogImageUrlApiModel("url", "status")
You right, why didn't you tell me this earlier :D, I had to change a lot of tests due to model change :d

2021-08-27 15:22 UTC, BorysChajdas commented on app/src/test/java/com/example/trainingintive/dog_images_feature/data/repository/DogImageRepositoryImplTest.kt
> +    val urlApiModel = DogImageUrlApiModel("url", "status")
Yeah :D I forgot to tell you this in the first PR :D

2021-08-31 11:25 UTC, VEndymionV requested changes

2021-08-31 11:25 UTC, VEndymionV commented on app/src/test/java/com/example/trainingintive/dog_images_feature/data/repository/DogImageRepositoryImplTest.kt
> +        val amountUrlsInDb = 1
Minor: You can inline it because you are using it only in one place and it isn't important for this test

2021-08-31 11:25 UTC, VEndymionV commented on app/src/test/java/com/example/trainingintive/dog_images_feature/data/repository/DogImageRepositoryImplTest.kt
> +        val amountUrlsInDb = 1
Same here and in other places, inline it, val is redundant here

2021-08-31 11:25 UTC, VEndymionV commented on app/src/test/java/com/example/trainingintive/dog_images_feature/data/repository/DogImageRepositoryImplTest.kt
> +        val expected = urlApiModel.toDomain(amountUrlsInDb)
Mock `toDomain` on urlApiModel to return your expected mock

2021-08-31 11:25 UTC, VEndymionV commented on app/src/test/java/com/example/trainingintive/dog_images_feature/data/repository/DogImageRepositoryImplTest.kt
> +        val dbModels: List<DogImageUrlDb> = listOf(
Just use mock here: `dbModels: List<DogImageUrlDb> = mockk()`

2021-08-31 11:25 UTC, VEndymionV commented on app/src/test/java/com/example/trainingintive/dog_images_feature/data/repository/DogImageRepositoryImplTest.kt
> +        val expected = dbModels.map { it.toDomain() }
Mock dbModels mock to return expected value

2021-08-31 11:25 UTC, VEndymionV commented on app/src/test/java/com/example/trainingintive/dog_images_feature/data/repository/DogImageRepositoryImplTest.kt
> +        every { urlDomain.toDatabaseEntity() } returns mockk(relaxed = true)
I see that you are using `relaxed = true` in a lot of places, please make sure that you are using it only if it's required, if you can write a test without it don't use it

2021-08-31 11:25 UTC, VEndymionV commented on app/src/test/java/com/example/trainingintive/dog_images_feature/data/repository/DogImageRepositoryImplTest.kt
> +        val valueToInsert = urlDomain.toDatabaseEntity()
Create `val valueToInsert = mockk()` at the top of the file and return it from `every { urlDomain.toDatabaseEntity() } returns valueToInsert`. Same in other places

2021-08-31 11:25 UTC, VEndymionV commented on app/src/test/java/com/example/trainingintive/dog_images_feature/data/repository/DogImageRepositoryImplTest.kt
> +        val urls: List<DogImageUrl> = listOf(
Try to rewrite this test to make `urls` a mock

2021-09-01 08:28 UTC, VEndymionV approved these changes

2021-09-01 08:28 UTC, VEndymionV commented on app/src/test/java/com/example/trainingintive/dog_images_feature/data/repository/DogImageRepositoryImplTest.kt
> +        val urlApiModel: DogImageUrlApiModel = mockk()
Minor: Could be also inlined because you are using it only in one place :)

2021-09-01 08:28 UTC, VEndymionV commented on app/src/test/java/com/example/trainingintive/dog_images_feature/data/repository/DogImageRepositoryImplTest.kt
> +        val expected = listOf(dbModels[1],dbModels[0])
Keep `val` before `every` blocks, don't mix order

2021-09-01 08:59 UTC, merged