fix dogviewmodel test
bartek977/TrainingIntive pull request #56
Opened 2021-08-26 07:08 UTC by bartek977

2021-08-27 14:56 UTC, BorysChajdas requested changes

2021-08-27 14:56 UTC, BorysChajdas commented on app/src/test/java/com/example/trainingintive/dog_images_feature/presentation/DogImageViewModelTest.kt
> +    fun createViewModel() =
Avoid helper functions in tests for simplicity, just inline it :)

2021-08-27 14:56 UTC, BorysChajdas commented on app/src/test/java/com/example/trainingintive/dog_images_feature/presentation/DogImageViewModelTest.kt
> +        every { insertDogImageUrlUseCase.execute(ofType(DogImageUrl::class)) } returns Completable.complete()
Can you use `any()` instead of `ofType(DogImageUrl::class)`?

2021-08-27 14:56 UTC, BorysChajdas commented on app/src/test/java/com/example/trainingintive/dog_images_feature/presentation/DogImageViewModelTest.kt
> +    val sampleDog = DogImageUrl(sampleImageUrl, 0)
Use mock instead of real object if it's possible

2021-08-30 08:41 UTC, bartek977 commented on app/src/test/java/com/example/trainingintive/dog_images_feature/presentation/DogImageViewModelTest.kt
> +    fun createViewModel() =
but in my opinion this improves readability :)

2021-08-31 11:27 UTC, VEndymionV commented on app/src/test/java/com/example/trainingintive/dog_images_feature/presentation/DogImageViewModelTest.kt
> +    fun createViewModel() =
But on the other hand, it makes your tests harder to analyze because you need to jump between functions. Tests should be as simple as possible.

2021-08-31 11:29 UTC, VEndymionV requested changes

2021-08-31 11:29 UTC, VEndymionV commented on app/src/test/java/com/example/trainingintive/dog_images_feature/presentation/DogImageViewModelTest.kt
> +    val sampleDog: DogImageUrl = mockk(relaxed = true)
Avoid creating a lot of models in test file, when it is possible try to create them in function

2021-09-01 08:30 UTC, VEndymionV approved these changes

2021-09-01 08:30 UTC, VEndymionV commented on app/src/test/java/com/example/trainingintive/dog_images_feature/presentation/DogImageViewModelTest.kt
> +        every { getDogImageUrlUseCase.execute() } returns Single.just(sampleDog)
Move `every` blocks after `val`s

2021-09-01 09:30 UTC, merged